### PR TITLE
Encode values issue

### PR DESCRIPTION
**Pull request by jacyzon**
ref #5

Please take a look, now should passed the test 
'Check that the created unit file\'s ExecStart line begins with an absolute path'.

The docker image lukebond/paz-service-directory is no longer exist on the docker hub, I had to update the fig.yml file. Same issue in the sub project paz-orchestrator.

However, I can't starting the scheduler server for some reason,
(hit the issue https://github.com/mgutz/execSync/issues/27)
and notice that execSync is no longer maintained.

``` bash
root@dev2:~/paz-scheduler# fig up
Recreating pazscheduler_svcdir_1...
Recreating pazscheduler_etcd_1...
Recreating pazscheduler_scheduler_1...
Attaching to pazscheduler_svcdir_1, pazscheduler_etcd_1, pazscheduler_scheduler_1
etcd_1      | [etcd] Mar 30 17:59:09.570 WARNING   | Using the directory c599a11acf55.etcd as the etcd curation directory because a directory was not specified.
etcd_1      | [etcd] Mar 30 17:59:09.572 INFO      | c599a11acf55 is starting a new cluster
etcd_1      | [etcd] Mar 30 17:59:09.593 INFO      | etcd server [name c599a11acf55, listen on :4001, advertised url http://127.0.0.1:4001]
etcd_1      | [etcd] Mar 30 17:59:09.639 INFO      | peer server [name c599a11acf55, listen on :7001, advertised url http://127.0.0.1:7001]
etcd_1      | [etcd] Mar 30 17:59:09.640 INFO      | c599a11acf55 starting in peer mode
etcd_1      | [etcd] Mar 30 17:59:09.642 INFO      | c599a11acf55: state changed from 'initialized' to 'follower'.
etcd_1      | [etcd] Mar 30 17:59:09.642 INFO      | c599a11acf55: state changed from 'follower' to 'leader'.
etcd_1      | [etcd] Mar 30 17:59:09.645 INFO      | c599a11acf55: leader changed from '' to 'c599a11acf55'.
svcdir_1    | Starting server
svcdir_1    | {"name":"paz-service-directory_log","hostname":"d144b79c6ce8","pid":6,"level":30,"msg":"paz-service-directory is now running on port 9001","time":"2015-03-30T17:59:09.998Z","v":0}
scheduler_1 | module.js:338
scheduler_1 |     throw err;
scheduler_1 |           ^
scheduler_1 | Error: Cannot find module './build/Release/shell'
scheduler_1 |     at Function.Module._resolveFilename (module.js:336:15)
scheduler_1 |     at Function.Module._load (module.js:278:25)
scheduler_1 |     at Module.require (module.js:365:17)
scheduler_1 |     at require (module.js:384:17)
scheduler_1 |     at Object.<anonymous> (/usr/src/app/node_modules/execSync/index.js:30:11)
scheduler_1 |     at Module._compile (module.js:460:26)
scheduler_1 |     at Object.Module._extensions..js (module.js:478:10)
scheduler_1 |     at Module.load (module.js:355:32)
scheduler_1 |     at Function.Module._load (module.js:310:12)
scheduler_1 |     at Module.require (module.js:365:17)
pazscheduler_scheduler_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping pazscheduler_etcd_1...
Stopping pazscheduler_svcdir_1...
```

``` bash
root@dev2:~/paz-scheduler# npm test

> paz-scheduler@0.0.1 test /root/paz-scheduler
> fig up -d && lab && fig stop

Recreating pazscheduler_svcdir_1...
Recreating pazscheduler_etcd_1...
Recreating pazscheduler_scheduler_1...


  xxxx......xxx

Test script errors:

Could not deploy service: Error: connect ECONNREFUSED


There were 1 test script error(s).

Failed tests:

  1) hooks/deploy POST /hooks/deploy should return a 200 status code depending on body of request:

      Error: connect ECONNREFUSED

      at errnoException (net.js:905:11)
      at Object.afterConnect [as oncomplete] (net.js:896:19)

  2) hooks/deploy POST /hooks/deploy should return a 400 status code if there is no service name:

      Error: connect ECONNREFUSED

      at errnoException (net.js:905:11)
      at Object.afterConnect [as oncomplete] (net.js:896:19)

  3) hooks/dockerhub POST /hooks/dockerhub should return a 200 status code when a correct request body is sent:

      Error: connect ECONNREFUSED

      at errnoException (net.js:905:11)
      at Object.afterConnect [as oncomplete] (net.js:896:19)

  4) hooks/dockerhub POST /hooks/dockerhub should return a 400 status code when an incorrect request body is sent:

      Error: connect ECONNREFUSED

      at errnoException (net.js:905:11)
      at Object.afterConnect [as oncomplete] (net.js:896:19)

  11) config GET /config/:name/version/latest returns 200 with a config:





  12) config GET /config/:name/version/:version should return 200 with a config doc:





  13) config GET /config/:name/version/:version should return 404 when version doesn't exist:






7 of 13 tests failed
Test duration: 9161 ms
No global variable leaks detected

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

Since it's an open source project I think it would be great to have a public CI like travis.io integrated so that it will shows the test result for each PR =)

### CODE REVIEW

**Comment by lukebond** [comment]
Let's see how it goes in CI. Looks like good work, thanks @Jacyzon will report back.

**Comment by lukebond** [comment]
It hasn't worked but I've noticed a few problems. Dockerfile is a bit out of date and a few other things. Looking into it.

**Comment by lukebond** [comment]
Fixed in f3b15f0228d5e57e3625629b54d5a0c271926ff1.

A couple of things FYI @Jacyzon:
- The Dockerfile was using Node 0.12 which is what was causing your `./build/release/shell` issue. I don't know why but plan to upgrade some other time
- The ECONNREFUSED I'm guessing is because you're running on OS X and the tests are assuming the containers are bound to ports on localhost. You need to run the tests like so on OSX:

```
$ DOCKER_IP=192.168.59.103 npm test
```

**Comment by lukebond** [comment]
Tests are now passing. Thanks so much for your fix @Jacyzon I really appreciate it.

**Comment by jacyzon** [comment]
Got it, thank you =)

**Comment by lukebond** [comment]
Yes, public CI like Travis would be good but the way we're using Docker in the tests isn't allowed on Travis. I'd like to look into opening up the Strider CD server we use, just a matter of finding the time :)

**Comment by jacyzon** [comment]
Great!
Strider looks nice, thank you for mentioning that. (I'm looking for a CI + CD solution for our team recently)

**Pull request merged**
