### PR TITLE
[ci skip] api-blueprint

### PR DESCRIPTION
**Pull request by jacyzon**
**Preview**

**Old layout**
http://docs.pazscheduleroldview.apiary.io

**New three column layout**
http://docs.pazschedulernewview.apiary.io

@lukebond Should the docs links to apiary via your account?

### CODE REVIEW

**Comment by lukebond** [comment]
Thanks @jacyzon! LGTM

BTW, what do you think of api-blueprint and apiary now that you've used it? I think it's quite nice but I still feel it's not the perfect solution.

Re putting them in my account, you remind me that I need to create an account for Paz.

I like the 3-column layout btw!

**Comment by jacyzon** [comment]
The repo can be linked to apiary so the online documentation gets updated. =)

Other good solution http://swagger.io but need a server to serve the docs site.

**Comment by jacyzon** [comment]
I think I misunderstood your meaning, but for me so far so good.
Why you think it's not a perfect solution?

**Comment by lukebond** [comment]
If you know how to link the GitHub blueprint files to apiary I'd love that! I didn't know it could be done.

Re why I don't think it's perfect, I have mixed feelings. I like keeping API docs separate from the code, ie. not annotated, I think the docs look nice when rendered, and I like that it's markdown. But I find the blueprint spec to be a bit messy and unclear. Also I was "downvoting" it because I didn't know you could link it to GitHub.

**Comment by jacyzon** [comment]
You might want to create a bot account at github and add it into Paz organization, then use that account to link to apiary. The bot account also usually useful for granting CI system access to github repos.

Go to apiary setting page, on the bottom there is a "connect to Github" button.

selection_005

Once it's connected to the apiary, apiary will use the account you linked to make a new commit for transferring blueprint from apiary which add a new file called "apiary.apib" on the root of the repo, then the docs folder can be removed.

**Pull request merged**
