### PR TITLE
Use older version of ini package due to safe encode values with '=' changed in 1.3.3

### PR DESCRIPTION
**Pull request by jacyzon**
ref #3 

https://github.com/isaacs/ini/commit/9c3b405331f7e0a0c624fe6ae6be4af3b1460978

### CODE REVIEW

**Comment by lukebond** [comment]
Thanks @Jacyzon!!!! :)

**Comment by jacyzon** [comment]
Or should we use ' ' instead of '=' ?

Like so

``` js
iniObj.Service.ExecStart = '/usr/bin/docker run --name ' + unitName;
```

rather than

``` js
iniObj.Service.ExecStart = '/usr/bin/docker run --name= ' + unitName;
```

**Comment by lukebond** [comment]
Whoops pulled the trigger already

**Comment by jacyzon** [comment]
But both would be ok =)

**Comment by lukebond** [comment]
After pulling it doesn't pass the tests in CI. If you have a chance to make them pass that'd be great. Otherwise I'll take a look in a few days (sorry, very busy week this week).

**Pull request merged**
